# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='title image')),
                ('short_description', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'verbose_name': 'Property',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'ordering': ['-created'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='properties',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gofriends_site.MenuItems'),
        ),
    ]
