# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0002_auto_20180214_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='properties',
            name='menu_item',
            field=models.ManyToManyField(blank=True, to='gofriends_site.MenuItems'),
        ),
    ]
