# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0003_auto_20180214_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='properties',
            name='menu_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gofriends_site.MenuItems'),
        ),
    ]
