# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0006_auto_20180215_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='url_field',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
