# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 10:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0007_items_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='items',
            name='url_field',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
