# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0009_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'verbose_name': 'Contacts',
            },
        ),
    ]
