# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 13:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0012_auto_20180216_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+380441234567'. Up to 12 digits allowed.", regex='^\\+?\\d{9,12}$')]),
        ),
    ]
