# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0014_auto_20180221_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About us', 'verbose_name_plural': '5. About us'},
        ),
        migrations.AlterModelOptions(
            name='casestudies',
            options={'ordering': ['-created'], 'verbose_name': 'Case Study', 'verbose_name_plural': '1. Case Studies'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': '6. Contacts'},
        ),
        migrations.AlterModelOptions(
            name='industries',
            options={'ordering': ['-created'], 'verbose_name': 'Industry', 'verbose_name_plural': '3. Industries'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created'], 'verbose_name': 'Service', 'verbose_name_plural': '2. Services'},
        ),
        migrations.AlterModelOptions(
            name='technologies',
            options={'ordering': ['-created'], 'verbose_name': 'Technology', 'verbose_name_plural': '4. Technologies'},
        ),
    ]
