# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0016_auto_20180221_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('keywords', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Meta tags',
                'verbose_name': 'Meta tag',
            },
        ),
    ]
