# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0017_metatags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
