# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0020_auto_20180221_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banner', models.ImageField(upload_to='banners')),
            ],
            options={
                'verbose_name_plural': 'Home banners',
                'ordering': ['-created'],
                'abstract': False,
                'verbose_name': 'Home banner',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['created'], 'verbose_name': 'Service', 'verbose_name_plural': '2. Services'},
        ),
    ]
