# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0021_auto_20180221_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='industries',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='industries/icons'),
        ),
    ]
