# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 08:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofriends_site', '0022_industries_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('position', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('photo', models.ImageField(upload_to='testimonials/photos')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='industries',
            options={'ordering': ['created'], 'verbose_name': 'Industry', 'verbose_name_plural': '3. Industries'},
        ),
    ]
